ERROR 2024-11-08 14:17:54,383 views An error occurred in the index view: division by zero
ERROR 2024-11-09 09:59:20,359 log Internal Server Error: /bag/add/365223332/
Traceback (most recent call last):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\bag\views.py", line 40, in add_to_bag
    product = get_object_or_404(Product, printful_id=printful_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
products.models.Product.MultipleObjectsReturned: get() returned more than one Product -- it returned 5!
ERROR 2024-11-09 09:59:20,518 basehttp "POST /bag/add/365223332/ HTTP/1.1" 500 92506
ERROR 2024-11-09 09:59:20,518 basehttp "POST /bag/add/365223332/ HTTP/1.1" 500 92506
ERROR 2024-11-09 09:59:56,746 log Internal Server Error: /bag/add/365223332/
Traceback (most recent call last):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\bag\views.py", line 40, in add_to_bag
    product = get_object_or_404(Product, printful_id=printful_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
products.models.Product.MultipleObjectsReturned: get() returned more than one Product -- it returned 5!
ERROR 2024-11-09 09:59:56,882 basehttp "POST /bag/add/365223332/ HTTP/1.1" 500 92712
ERROR 2024-11-09 09:59:56,882 basehttp "POST /bag/add/365223332/ HTTP/1.1" 500 92712
ERROR 2024-11-09 10:07:34,736 log Internal Server Error: /products/353888632/
Traceback (most recent call last):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\products\views.py", line 80, in product_detail
    return render(request, 'products/product_detail.html', {'product_variants': product_variants})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\bag\contexts.py", line 22, in bag_contents
    subtotal = quantity * product.price
               ~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'dict' and 'decimal.Decimal'
ERROR 2024-11-09 10:07:34,869 basehttp "GET /products/353888632/ HTTP/1.1" 500 114914
ERROR 2024-11-09 10:07:34,869 basehttp "GET /products/353888632/ HTTP/1.1" 500 114914
ERROR 2024-11-09 10:07:42,026 log Internal Server Error: /products/365223332/
Traceback (most recent call last):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\products\views.py", line 80, in product_detail
    return render(request, 'products/product_detail.html', {'product_variants': product_variants})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\bag\contexts.py", line 22, in bag_contents
    subtotal = quantity * product.price
               ~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'dict' and 'decimal.Decimal'
ERROR 2024-11-09 10:07:42,170 basehttp "GET /products/365223332/ HTTP/1.1" 500 115643
ERROR 2024-11-09 10:07:42,170 basehttp "GET /products/365223332/ HTTP/1.1" 500 115643
ERROR 2024-11-09 10:07:48,778 log Internal Server Error: /products/365223332/
Traceback (most recent call last):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\products\views.py", line 80, in product_detail
    return render(request, 'products/product_detail.html', {'product_variants': product_variants})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\bag\contexts.py", line 22, in bag_contents
    subtotal = quantity * product.price
               ~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'dict' and 'decimal.Decimal'
ERROR 2024-11-09 10:07:48,903 basehttp "GET /products/365223332/ HTTP/1.1" 500 115643
ERROR 2024-11-09 10:07:48,903 basehttp "GET /products/365223332/ HTTP/1.1" 500 115643
ERROR 2024-11-09 10:08:00,875 log Internal Server Error: /products/353888632/
Traceback (most recent call last):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\products\views.py", line 80, in product_detail
    return render(request, 'products/product_detail.html', {'product_variants': product_variants})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Corsair\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsair\Desktop\Kicassoo-Django\Kicassoo\bag\contexts.py", line 22, in bag_contents
    subtotal = quantity * product.price
               ~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'dict' and 'decimal.Decimal'
ERROR 2024-11-09 10:08:01,124 basehttp "GET /products/353888632/ HTTP/1.1" 500 114767
ERROR 2024-11-09 10:08:01,124 basehttp "GET /products/353888632/ HTTP/1.1" 500 114767
